"""Tambah kolom dinas dan total_hari di absensi_ringkasan_karyawan

Revision ID: 32aea9db4e34
Revises: 3999c0a6b975
Create Date: 2026-09-23 11:48:53.624709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aea9db4e34'
down_revision = '3999c0a6b975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_ringkasan_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dinas', sa.Numeric(precision=6, scale=1), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_hari', sa.Numeric(precision=6, scale=1), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_ringkasan_karyawan', schema=None) as batch_op:
        batch_op.drop_column('total_hari')
        batch_op.drop_column('dinas')

    # ### end Alembic commands ###
