"""Tambah dukungan input absensi manual per periode

Revision ID: 3999c0a6b975
Revises: bc1aa88d74af
Create Date: 2026-09-22 15:09:51.571875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3999c0a6b975'
down_revision = 'bc1aa88d74af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periode_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absensi_manual', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periode_payroll', schema=None) as batch_op:
        batch_op.drop_column('absensi_manual')

    # ### end Alembic commands ###
