"""Ganti tunjangan masa kerja jadi field manual per karyawan

Revision ID: 6905b569fa6d
Revises: 6ca01c97fd93
Create Date: 2026-09-22 12:12:01.091627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6905b569fa6d'
down_revision = '6ca01c97fd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tunjangan_masa_kerja_jenjang')
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tunjangan_masa_kerja', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # Bersihkan menu "master_tunjangan" (dan hak akses terkait) yang sudah tidak dipakai
    op.execute(
        "DELETE FROM hak_akses WHERE menu_id IN (SELECT id FROM menu WHERE kode_menu = 'master_tunjangan')"
    )
    op.execute("DELETE FROM menu WHERE kode_menu = 'master_tunjangan'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_column('tunjangan_masa_kerja')

    op.create_table('tunjangan_masa_kerja_jenjang',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('min_bulan', sa.INTEGER(), nullable=False),
    sa.Column('max_bulan', sa.INTEGER(), nullable=True),
    sa.Column('nominal', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
