"""Tambah jenis dan keterangan di DepositTransaksi untuk penyesuaian saldo manual

Revision ID: 6ca01c97fd93
Revises: c73f1d14a3f8
Create Date: 2026-09-22 11:56:52.809306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca01c97fd93'
down_revision = 'c73f1d14a3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis', sa.String(length=20), nullable=False, server_default='otomatis'))
        batch_op.add_column(sa.Column('keterangan', sa.String(length=255), nullable=True))
        batch_op.alter_column('periode',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_transaksi', schema=None) as batch_op:
        batch_op.alter_column('periode',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.drop_column('keterangan')
        batch_op.drop_column('jenis')

    # ### end Alembic commands ###
