"""Fase 4: Berita Acara dan Cicilan

Revision ID: 6d6667beb54d
Revises: f631ae7048bf
Create Date: 2026-09-18 13:15:02.592876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6667beb54d'
down_revision = 'f631ae7048bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reason_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('kasus_berita_acara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awb', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=True),
    sa.Column('reason_claim_id', sa.Integer(), nullable=True),
    sa.Column('nominal_prediksi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tanggal_prediksi', sa.Date(), nullable=True),
    sa.Column('keterangan_prediksi', sa.Text(), nullable=True),
    sa.Column('nominal_pusat', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('periode_pusat', sa.String(length=30), nullable=True),
    sa.Column('tahun_pusat', sa.String(length=10), nullable=True),
    sa.Column('jenis_ecommerce', sa.String(length=100), nullable=True),
    sa.Column('lokasi_tertagih', sa.String(length=150), nullable=True),
    sa.Column('mitra', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('rm', sa.String(length=100), nullable=True),
    sa.Column('status_bayar', sa.String(length=50), nullable=True),
    sa.Column('keterangan_pusat', sa.Text(), nullable=True),
    sa.Column('keputusan', sa.String(length=20), nullable=True),
    sa.Column('jumlah_bulan_cicilan', sa.Integer(), nullable=True),
    sa.Column('nominal_final', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['reason_claim_id'], ['reason_claim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('awb')
    )
    op.create_table('cicilan_berita_acara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kasus_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_bulan', sa.Integer(), nullable=False),
    sa.Column('nominal_per_bulan', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_sisa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kasus_id'], ['kasus_berita_acara.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kasus_id')
    )
    op.create_table('potongan_berita_acara_periode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('kasus_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['kasus_id'], ['kasus_berita_acara.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potongan_berita_acara_periode')
    op.drop_table('cicilan_berita_acara')
    op.drop_table('kasus_berita_acara')
    op.drop_table('reason_claim')
    # ### end Alembic commands ###
