"""Tambah model periode payroll, absensi ringkasan, slip gaji

Revision ID: 776a3ec379cf
Revises: 87fa707079d9
Create Date: 2026-09-18 12:57:01.314430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776a3ec379cf'
down_revision = '87fa707079d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periode_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('difinalisasi_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun', 'bulan', name='uq_periode_tahun_bulan')
    )
    op.create_table('absensi_ringkasan_karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('sakit', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('izin', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('tidak_finger', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('alpha_tdk_finger', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('cuti', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('off', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('potongan_terlambat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ditarik_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_payroll_id', 'karyawan_id', name='uq_absensi_periode_karyawan')
    )
    op.create_table('slip_gaji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('gaji_pokok_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tunjangan_masa_kerja_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('insentif', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('thr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_deposit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_kehadiran', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_terlambat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_lainnya', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_pph21', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_bpjs_tk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reward', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_reward', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_berita_acara', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_bbm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('potongan_phl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_thp', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_akhir', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_payroll_id', 'karyawan_id', name='uq_slip_periode_karyawan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slip_gaji')
    op.drop_table('absensi_ringkasan_karyawan')
    op.drop_table('periode_payroll')
    # ### end Alembic commands ###
