"""Inisialisasi model data master, user, dan hak akses

Revision ID: 87fa707079d9
Revises: 
Create Date: 2026-09-17 18:07:07.207670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fa707079d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jabatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('gaji_pokok_default', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_menu', sa.String(length=50), nullable=False),
    sa.Column('nama_menu', sa.String(length=100), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_menu')
    )
    op.create_table('pengaturan_deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_potongan_bulanan', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tunjangan_masa_kerja_jenjang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_bulan', sa.Integer(), nullable=False),
    sa.Column('max_bulan', sa.Integer(), nullable=True),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hak_akses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jabatan_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('level_akses', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['jabatan_id'], ['jabatan.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jabatan_id', 'menu_id', name='uq_hak_akses_jabatan_menu')
    )
    op.create_table('karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_dp', sa.String(length=20), nullable=False),
    sa.Column('nik_karyawan', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('jabatan_id', sa.Integer(), nullable=False),
    sa.Column('npwp', sa.String(length=30), nullable=True),
    sa.Column('nik_ktp', sa.String(length=30), nullable=True),
    sa.Column('rekening_bank', sa.String(length=100), nullable=True),
    sa.Column('alamat_npwp', sa.Text(), nullable=True),
    sa.Column('status_pajak', sa.String(length=10), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('tanggal_join', sa.Date(), nullable=True),
    sa.Column('tanggal_resign', sa.Date(), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=False),
    sa.Column('limit_deposit_individual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('potongan_bpjs_tk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jabatan_id'], ['jabatan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik_karyawan')
    )
    op.create_table('deposit_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('saldo_terkumpul', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('karyawan_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('karyawan_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deposit_transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_saldo_id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=7), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_setelah', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deposit_saldo_id'], ['deposit_saldo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposit_transaksi')
    op.drop_table('user')
    op.drop_table('deposit_saldo')
    op.drop_table('karyawan')
    op.drop_table('hak_akses')
    op.drop_table('tunjangan_masa_kerja_jenjang')
    op.drop_table('pengaturan_deposit')
    op.drop_table('menu')
    op.drop_table('jabatan')
    # ### end Alembic commands ###
