"""Tambah override nama sheet rekap dan kode periode keterlambatan

Revision ID: 8e4ffff6a813
Revises: 6d6667beb54d
Create Date: 2026-09-22 11:42:44.403767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4ffff6a813'
down_revision = '6d6667beb54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periode_payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_sheet_rekap_override', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kode_periode_terlambat_override', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periode_payroll', schema=None) as batch_op:
        batch_op.drop_column('kode_periode_terlambat_override')
        batch_op.drop_column('nama_sheet_rekap_override')

    # ### end Alembic commands ###
