"""Tambah fitur Tambahan (JenisTambahan, TambahanEntry) dan pindahkan Reward ke sebelum THP

Revision ID: b9f35570cd44
Revises: 32aea9db4e34
Create Date: 2026-09-23 19:23:06.522767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f35570cd44'
down_revision = '32aea9db4e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_tambahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('tambahan_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jenis_tambahan_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jenis_tambahan_id'], ['jenis_tambahan.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slip_gaji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tambahan', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # Seed jenis tambahan awal (tim bisa tambah/hapus lagi sendiri lewat halaman master)
    jenis_tambahan_table = sa.table('jenis_tambahan', sa.column('nama', sa.String))
    op.bulk_insert(jenis_tambahan_table, [
        {'nama': 'Tambahan Mitra'},
        {'nama': 'Lembur'},
        {'nama': 'KPI COD'},
        {'nama': 'Tambahan Grade'},
        {'nama': 'Tambahan Lain'},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slip_gaji', schema=None) as batch_op:
        batch_op.drop_column('tambahan')

    op.drop_table('tambahan_entry')
    op.drop_table('jenis_tambahan')
    # ### end Alembic commands ###
