"""Pisahkan default limit deposit dari default potongan bulanan

Revision ID: c73f1d14a3f8
Revises: 8e4ffff6a813
Create Date: 2026-09-22 11:47:42.537359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73f1d14a3f8'
down_revision = '8e4ffff6a813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan_deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_limit_deposit', sa.Numeric(precision=14, scale=2), nullable=False, server_default='4100000'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan_deposit', schema=None) as batch_op:
        batch_op.drop_column('default_limit_deposit')

    # ### end Alembic commands ###
