"""Tambah riwayat kenaikan tunjangan masa kerja (TunjanganTransaksi)

Revision ID: d1f2df00e572
Revises: 6905b569fa6d
Create Date: 2026-09-22 14:08:31.847608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f2df00e572'
down_revision = '6905b569fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunjangan_transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('nominal_perubahan', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_setelah', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tunjangan_transaksi')
    # ### end Alembic commands ###
