"""Ganti Potongan Lainnya jadi sistem jenis seperti Tambahan

Revision ID: f5652c3ab675
Revises: b9f35570cd44
Create Date: 2026-09-23 20:15:02.154531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5652c3ab675'
down_revision = 'b9f35570cd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_potongan_lainnya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('potongan_lainnya_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jenis_potongan_lainnya_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jenis_potongan_lainnya_id'], ['jenis_potongan_lainnya.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed jenis awal (tim bisa tambah/hapus sendiri lewat halaman master) --
    # sesuai pemetaan yang dikonfirmasi David dari sheet POTONGAN file referensi
    # (Denda Terlambat, Cicilan BA, Potongan PHL, Potongan Entertainment TIDAK
    # ikut di sini karena masing-masing sudah punya komponen tersendiri).
    jenis_table = sa.table('jenis_potongan_lainnya', sa.column('id', sa.Integer), sa.column('nama', sa.String))
    op.bulk_insert(jenis_table, [
        {'id': 1, 'nama': 'Pemotongan Lainnya'},
        {'id': 2, 'nama': 'Denda Administrasi'},
        {'id': 3, 'nama': 'Pemotongan Insentif Admin'},
        {'id': 4, 'nama': 'Pemotongan Penyesuaian PPPM'},
        {'id': 5, 'nama': 'Migrasi dari sistem lama'},
    ])

    # Migrasi baris KomponenUpload lama (jenis='potongan_lainnya') yang masih berupa
    # nominal generik (draft, belum final) ke tabel baru supaya tidak hilang begitu
    # saja -- ditandai jenis "Migrasi dari sistem lama" supaya tim bisa cek ulang.
    # Periode yang sudah final TIDAK terpengaruh sama sekali (nilai potongan_lainnya
    # di SlipGaji sudah tersimpan sebagai angka tetap, bukan dihitung ulang dari sini).
    conn = op.get_bind()
    baris_lama = conn.execute(sa.text(
        "SELECT periode_payroll_id, karyawan_id, nominal, keterangan "
        "FROM komponen_upload WHERE jenis = 'potongan_lainnya'"
    )).fetchall()
    if baris_lama:
        potongan_table = sa.table(
            'potongan_lainnya_entry',
            sa.column('periode_payroll_id', sa.Integer),
            sa.column('karyawan_id', sa.Integer),
            sa.column('jenis_potongan_lainnya_id', sa.Integer),
            sa.column('nominal', sa.Numeric(14, 2)),
            sa.column('keterangan', sa.String),
        )
        op.bulk_insert(potongan_table, [
            {
                'periode_payroll_id': row.periode_payroll_id,
                'karyawan_id': row.karyawan_id,
                'jenis_potongan_lainnya_id': 5,
                'nominal': row.nominal,
                'keterangan': row.keterangan,
            }
            for row in baris_lama
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potongan_lainnya_entry')
    op.drop_table('jenis_potongan_lainnya')
    # ### end Alembic commands ###
