"""Fase 3: komponen upload, reward, entertainment, PHL

Revision ID: f631ae7048bf
Revises: 776a3ec379cf
Create Date: 2026-09-18 13:07:02.797821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f631ae7048bf'
down_revision = '776a3ec379cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('entertainment_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('total_biaya', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phl_periode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('total_biaya', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_paket', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_payroll_id', name='uq_phl_periode')
    )
    op.create_table('phl_resi_karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phl_periode_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_resi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['phl_periode_id'], ['phl_periode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phl_periode_id', 'karyawan_id', name='uq_phl_resi_karyawan')
    )
    op.create_table('reward_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jenis_reward_id', sa.Integer(), nullable=True),
    sa.Column('entertainment_event_id', sa.Integer(), nullable=True),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entertainment_event_id'], ['entertainment_event.id'], ),
    sa.ForeignKeyConstraint(['jenis_reward_id'], ['jenis_reward.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komponen_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_payroll_id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=30), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('diunggah_oleh_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diunggah_oleh_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['periode_payroll_id'], ['periode_payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jabatan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kena_phl', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jabatan', schema=None) as batch_op:
        batch_op.drop_column('kena_phl')

    op.drop_table('komponen_upload')
    op.drop_table('reward_entry')
    op.drop_table('phl_resi_karyawan')
    op.drop_table('phl_periode')
    op.drop_table('entertainment_event')
    op.drop_table('jenis_reward')
    # ### end Alembic commands ###
